server:
  port: 8083

spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 823e9089-86ec-43e4-a116-3a4365581c32
    sentinel:
      transport:
        # 服务监控端口
        dashboard: localhost:8080

    gateway:
      discovery:
        locator:
          # 让gateway可以发现nacos中的微服务
          enabled: true
      routes:
          # 路由名称
        - id: user_routes
          # lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
          uri: lb://user-server
          # 路由的优先级,数字越小级别越高
          #order: 1
          # 断言(路由转发要满足的条件)
          predicates:
            #- Method=GET,POST
            - Path=/user/**

        - id: test_routes
          uri: lb://test-server
          predicates:
            - Path=/test/**
          filters:
            - Time=true
