
server:
  port: 8082

spring:
  application:
    # 服务名
    name: test-server

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 823e9089-86ec-43e4-a116-3a4365581c32
    sentinel:
      transport:
        # 服务监控端口
        dashboard: 127.0.0.1:8080

  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    database: 0
    lettuce:
      pool:
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 30000
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
    timeout: 3000


# 开启openFeign对sentinel的整合
feign:
  sentinel:
    enabled: true